### ISSUE TITLE
1.0.3 not available on pub.dev

### ISSUE THREAD

**Issue by dale-lakes** [justkawal/animated_text#7]
The README.md currently states the latest version of animated_text is 1.0.3 . But pub.dev currently states the latest version is 1.0.2. I believe some work was done to add null safety support, but that release has not been published to pub.dev.

**Comment by chrystoffer** [comment]
```
  animated_text:
    version: ^1.0.3
    git:
      url: https://github.com/josorio9111/animated_text.git
```
